# -*- coding: utf-8 -*-
"""Email spam .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lAe0EeCGRBT9ps6GrQkIXHELgLFFmpP
"""

import numpy as np
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Advait0801/SPPU-COMP-2019-Assignments/refs/heads/ML/Email%20Spam%20Classification/emails.csv')
df

print(df.info())
df.isnull().sum()

X=df.iloc[:,1:3001]
y=df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=2)

from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

from sklearn.svm import SVC
model=SVC()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

