# -*- coding: utf-8 -*-
"""Neural Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmfC675NBRoRxZ3FdtWrKwcJRR0pCPbt
"""

import pandas as pd

df=pd.read_csv('https://raw.githubusercontent.com/Tanmay49/SEM7/main/ML/Churn_Modelling.csv')

df.head()

df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)

gender=pd.get_dummies(df['Gender'],drop_first=True)
geography=pd.get_dummies(df['Geography'],drop_first=True)
df=pd.concat([df,gender,geography],axis=1)

df=df.drop(['Gender','Geography'],axis=1)
df.dropna()
df

X=df.drop(['Exited'],axis=1)
y=df['Exited']

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y)

from keras.models import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(activation='relu',units=6))
model.add(Dense(activation='relu',units=6))
model.add(Dense(activation='sigmoid',units=1))
model.compile(optimizer='adam',loss='binary_crossentropy')
model.fit(X_train,y_train,batch_size=10,epochs=50)

