# -*- coding: utf-8 -*-
"""uber price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekLm6T2xQYGGct9BDTS9rXyeFBesseHj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('https://raw.githubusercontent.com/Tanmay49/SEM7/main/ML/uber.csv')
df

df.head()



df=df.drop(['Unnamed: 0','key','pickup_datetime'],axis=1)
df.dropna(inplace=True)

sns.boxplot(df.fare_amount)

low=df.fare_amount.quantile(0.05)
high=df.fare_amount.quantile(0.95)
df=df[(df.fare_amount > low) & (df.fare_amount < high)]

sns.boxplot(df.fare_amount)

sns.heatmap(df.corr(),annot=True)

from sklearn.model_selection import train_test_split
X=df.drop(['fare_amount'],axis=1)
y=df.fare_amount

X_train,X_test,y_train,y_test=train_test_split(X,y)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

y_pred=lr.predict(X_test)

from sklearn.metrics import mean_squared_error,r2_score
print(np.sqrt(mean_squared_error(y_test,y_pred)))
print(r2_score(y_test,y_pred))

from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(X_train,y_train)
y_pred2=rf.predict(X_test)

from sklearn.metrics import mean_squared_error,r2_score
print(np.sqrt(mean_squared_error(y_test,y_pred2)))
print(r2_score(y_test,y_pred2))

