# -*- coding: utf-8 -*-
"""ML-A4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wOK2MfTvPg6mAhDnlMbAF3KyjDwZwwx
"""

start_x = 2
rate = 0.01
precision = 0.000001
step_size = 1
max_itr = 10000
itr = 0
df = lambda x:2*(x+3)
gd = []

while step_size >precision and itr < max_itr:
  prev = start_x
  start_x -= rate*df(prev)
  step_size = abs(prev - start_x)
  itr += 1
  print("iteraction ", itr ," -> Value =", start_x)
  gd.append(start_x)

print("local minimum occurs at ", start_x)

import seaborn as sns
  sns.scatterplot(gd)