# -*- coding: utf-8 -*-
"""ML-A2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OoiA2F49-iPMSbylhchxZH7y-rnhdY7n
"""

import pandas as pd

Data = pd.read_csv('https://raw.githubusercontent.com/Tanmay49/SEM7/main/ML/emails.csv')

Data.head()

X = Data.iloc[:,1:3001]
Y = Data.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X,Y)
y_pred = model.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

from sklearn.svm import SVC
model = SVC()
model.fit(X,Y)
y_pred = model.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))