# -*- coding: utf-8 -*-
"""ML-A5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1607j7Ph42FXck3zA5q0txGTy2bsXkr3L
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Tanmay49/SEM7/main/ML/sales_data_sample.csv',encoding = 'unicode_escape')
df.head()

df = df[['QUANTITYORDERED','PRICEEACH','SALES']]

from sklearn.cluster import KMeans
lis = []
for k in range(1,15):
  kmeans = KMeans(n_clusters = k)
  kmeans.fit(df)
  lis.append(kmeans.inertia_)

import seaborn as sns

sns.lineplot(x = range(1,15),y = lis)

# 4 is elbow as after that point no much change in value of
kmeans = KMeans(n_clusters = 4)
df['Cluster No.'] = kmeans.fit_predict(df)
df